image: Visual Studio 2017
version: 0.1-appveyor-{build}({branch})
before_build:
  - dir
  - ren ????????.sln HackerBomberScript.sln
  - nuget restore
configuration: Debug
build:
  project: HackerBomberScript.sln
  verbosity: minimal
after_build: # copy files and pack
  - msbuild /t:SignAndroidPackage C:\projects\hackerbomberscript\MobileBomber\MobileBomber.csproj
  - md C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\ScriptInterpreter\bin\Debug\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\HackerBomberApplication\bin\Debug\*.* C:\projects\hackerbomberscript\binaries
# - copy C:\projects\hackerbomberscript\HackerBomberCrossPlatform\bin\Debug\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\BomberStudio\bin\Debug\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\HackerBomber\bin\Debug\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\MobileBomber\bin\Debug\*.* C:\projects\hackerbomberscript\binaries
  - 7z a -tzip final.zip .\binaries\*
artifacts:
  - path: final.zip
    name: Everything here
  - path: MobileBomber\bin\Debug\com.companyname.mobilebomber-Signed.apk
    name: MobileBomber
  - path: ScriptInterpreter\bin\Debug\ScriptInterpreter.dll
    name: ScriptInterpreter